<a href="https://colab.research.google.com/github/NithyaStanly/internship/blob/main/Jun16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('welcome')

welcome


In [ ]:
print("welcome","to","the","session",sep="-")

welcome-to-the-session


In [ ]:
age=20
type(age)

int

In [ ]:
age="twenty"
type(age)

str

In [ ]:
tot_revenue = 35000
name = "roses and lillies"
print(name,tot_revenue)

roses and lillies 35000


In [ ]:
print(f"my business name is {name} and my revenue is {tot_revenue}")

my business name is roses and lillies and my revenue is 35000


In [ ]:
print("my business {} has revenue of {} rupees".format(name,tot_revenue))

my business roses and lillies has revenue of 35000 rupees


In [ ]:
name2=int(input("what is your age"))
print(type(name2))

what is your age20
<class 'int'>


In [ ]:
message = "its good to see you all."
len(message)

24

In [ ]:
message[0]

'i'

In [ ]:
message[-1]

'.'

In [ ]:
message[]

' '

In [ ]:
message2="See you ,tommorow"
new_msg=message+message2
new_msg

'its good to see you all.See you ,tommorow'

In [ ]:
print(message2.lower())

see you ,tommorow


In [ ]:
print(message2.strip())

See you ,tommorow


In [ ]:

print(message2.replace("See", "Python"))


Python you ,tommorow


In [ ]:

print(message2.split(","))


['See you ', 'tommorow']


In [ ]:
movies=[
    {"title":"Inception","year":2010,"ratings":[8,9,10,9]},
    {"title":"Titanic","year":1997,"ratings":[9,8,9,10]},
    {"title":"The Matrix","year":1999,"ratings":[10,9,10,10]},
    {"title":"Interstellar","year":2014,"ratings":[9,8,10,9]}
]

In [ ]:
new_movie = {"title": "Avengers", "year": 2019, "ratings": [9, 10, 9, 10]}
movies.append(new_movie)
print(movies)

[{'title': 'Inception', 'year': 2010, 'ratings': [8, 9, 10, 9]}, {'title': 'Titanic', 'year': 1997, 'ratings': [9, 8, 9, 10]}, {'title': 'The Matrix', 'year': 1999, 'ratings': [10, 9, 10, 10]}, {'title': 'Interstellar', 'year': 2014, 'ratings': [9, 8, 10, 9]}, {'title': 'Avengers', 'year': 2019, 'ratings': [9, 10, 9, 10]}]


In [ ]:

for movie in movies:
    if movie["title"] == "Titanic":
        movie["ratings"].extend([10, 9, 8])
        break
print(movies)

[{'title': 'Inception', 'year': 2010, 'ratings': [8, 9, 10, 9]}, {'title': 'Titanic', 'year': 1997, 'ratings': [9, 8, 9, 10, 10, 9, 8]}, {'title': 'The Matrix', 'year': 1999, 'ratings': [10, 9, 10, 10]}, {'title': 'Interstellar', 'year': 2014, 'ratings': [9, 8, 10, 9]}, {'title': 'Avengers', 'year': 2019, 'ratings': [9, 10, 9, 10]}]


In [ ]:
for movie in movies:
    ratings = movie["ratings"]
    avg = sum(ratings) / len(ratings)
    print(f"{movie['title']} → Average Rating: {avg:.2f}")


Inception → Average Rating: 9.00
Titanic → Average Rating: 9.00
The Matrix → Average Rating: 9.75
Interstellar → Average Rating: 9.00
Avengers → Average Rating: 9.50


In [ ]:
for movie in movies:
    if movie["title"] == "Titanic":
        movie["year"] = 1998
        break
print(movies)

[{'title': 'Inception', 'year': 2010, 'ratings': [8, 9, 10, 9]}, {'title': 'Titanic', 'year': 1998, 'ratings': [9, 8, 9, 10, 10, 9, 8]}, {'title': 'The Matrix', 'year': 1999, 'ratings': [10, 9, 10, 10]}, {'title': 'Interstellar', 'year': 2014, 'ratings': [9, 8, 10, 9]}, {'title': 'Avengers', 'year': 2019, 'ratings': [9, 10, 9, 10]}]


In [ ]:
highest_avg = 0
top_movie = ""

for movie in movies:
    avg = sum(movie["ratings"]) / len(movie["ratings"])
    if avg > highest_avg:
        highest_avg = avg
        top_movie = movie["title"]

print(f" Highest Rated Movie: {top_movie} → Average Rating: {highest_avg:.2f}")


 Highest Rated Movie: The Matrix → Average Rating: 9.75


In [ ]:
for movie in movies:
    if movie["title"] == "Interstellar":
        movies.remove(movie)
        break
print(movies)

[{'title': 'Inception', 'year': 2010, 'ratings': [8, 9, 10, 9]}, {'title': 'Titanic', 'year': 1998, 'ratings': [9, 8, 9, 10, 10, 9, 8]}, {'title': 'The Matrix', 'year': 1999, 'ratings': [10, 9, 10, 10]}, {'title': 'Avengers', 'year': 2019, 'ratings': [9, 10, 9, 10]}]


In [ ]:
for movie in movies:
    avg = sum(movie["ratings"]) / len(movie["ratings"])
    if avg >= 9:
        print(f"{movie['title']} → Average Rating: {avg:.2f}")


Inception → Average Rating: 9.00
Titanic → Average Rating: 9.00
The Matrix → Average Rating: 9.75
Avengers → Average Rating: 9.50


In [ ]:
def calculate_total(scores):
  return sum(scores)

In [ ]:
def calculate_avg(scores):
  if not scores:
    return 0
    return sum(scores)/len(scores)



In [ ]:
def determine_grade(avg):
    if avg >= 85:
        return 'A'
    elif avg >= 60:
        return 'B'
    elif avg >= 45:
        return 'C'
    else:
        return 'D'

    print(f"Total Score  : {total}")
    print(f"Average Score: {avg:.2f}")
    print(f"Grade        : {grade}")

In [ ]:
student=[
    {"subj":"english","score":35},
    {"subj":"maths","score":20},
    {"subj":"cs","score":47},
    {"subj":"hindi","score":30},
]
print

In [ ]:
import numpy as np

In [ ]:
my_list=[1,2,3,4]
type(my_list)

list

In [ ]:
my_arr=np.array(my_list)
type(my_arr)

numpy.ndarray

In [ ]:
my_list

[1, 2, 3, 4]

In [ ]:
my_arr.shape

(4,)

In [ ]:
my_arr.size

4

In [ ]:
my_arr.ndim

1

In [ ]:
my_arr[3]

np.int64(4)

In [ ]:
my_arr2=np.array([
    [1,12,23,4],
    [5,26,17,8],
    [45,21,61,83]
])
my_arr2

array([[ 1, 12, 23,  4],
       [ 5, 26, 17,  8],
       [45, 21, 61, 83]])

In [ ]:
my_arr2.shape


(2, 4)

In [ ]:
my_arr2.shape


8

In [ ]:
np.max(my_arr2)

np.int64(26)

In [ ]:
np.sort(my_arr2)

array([[ 1,  4, 12, 23],
       [ 5,  8, 17, 26]])

In [ ]:
np.min(my_arr2)

np.int64(1)

In [ ]:
np.sum(my_arr2)

np.int64(96)

In [ ]:
my_arr2

array([[ 1, 12, 23,  4],
       [ 5, 26, 17,  8]])

In [ ]:
my_arr2[1:,2:]

array([[17,  8]])

In [ ]:
np.transpose(my_arr2)

array([[ 1,  5, 45],
       [12, 26, 21],
       [23, 17, 61],
       [ 4,  8, 83]])

In [ ]:
reshaped_arr = my_arr2.reshape(4, 3)
print(reshaped_arr)

[[ 1 12 23]
 [ 4  5 26]
 [17  8 45]
 [21 61 83]]


In [ ]:
print( np.argmax(my_arr2))


11


In [ ]:
print( np.unique(my_arr2))

[ 1  4  5  8 12 17 21 23 26 45 61 83]


In [ ]:
print( np.where(my_arr2 > 20))


(array([0, 1, 2, 2, 2, 2]), array([2, 1, 0, 1, 2, 3]))


In [ ]:
range_arr = np.arange(1, 13).reshape(3, 4)
print( range_arr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print("Diagonal elements:", my_arr2.diagonal())


[ 1 26 61]


In [ ]:
np.random.random((4,3))

array([[0.56023098, 0.50086226, 0.33503294],
       [0.44252808, 0.13356174, 0.23041651],
       [0.10467593, 0.81745399, 0.27189542],
       [0.04744532, 0.64298269, 0.68364499]])

In [ ]:
np.random.randint(10,100,(2,6))

array([[76, 35, 50, 70, 58, 82],
       [57, 50, 36, 96, 87, 30]])